# Generated by Django 5.0.1 on 2026-05-17 19:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("places", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="place",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="created_places",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Created by",
            ),
        ),
        migrations.AddField(
            model_name="placeimage",
            name="place",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="images",
                to="places.place",
                verbose_name="Place",
            ),
        ),
        migrations.AddField(
            model_name="place",
            name="tags",
            field=models.ManyToManyField(
                blank=True,
                related_name="places",
                to="places.placetag",
                verbose_name="Tags",
            ),
        ),
        migrations.AddConstraint(
            model_name="placeimage",
            constraint=models.UniqueConstraint(
                fields=("place", "order"), name="unique_place_image_order"
            ),
        ),
        migrations.AddIndex(
            model_name="place",
            index=models.Index(
                fields=["category", "is_active"], name="idx_place_category_active"
            ),
        ),
        migrations.AddIndex(
            model_name="place",
            index=models.Index(
                fields=["is_featured", "is_active"], name="idx_place_featured_active"
            ),
        ),
        migrations.AddIndex(
            model_name="place",
            index=models.Index(fields=["latitude", "longitude"], name="idx_place_geo"),
        ),
        migrations.AddIndex(
            model_name="place",
            index=models.Index(
                fields=["-average_rating"], name="idx_place_rating_desc"
            ),
        ),
        migrations.AddIndex(
            model_name="place",
            index=models.Index(fields=["-view_count"], name="idx_place_views_desc"),
        ),
        migrations.AddIndex(
            model_name="place",
            index=models.Index(
                fields=["price_level", "is_active"], name="idx_place_price_active"
            ),
        ),
    ]
