# Generated by Django 5.0.1 on 2026-05-17 19:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("favorites", "0001_initial"),
        ("places", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="favorite",
            name="place",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="favorited_by",
                to="places.place",
                verbose_name="Place",
            ),
        ),
    ]
