# Generated by Django 5.0.1 on 2026-05-17 19:33

import django.db.models.deletion
import routes.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("places", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="RoutePlace",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "order",
                    models.PositiveSmallIntegerField(
                        default=1,
                        help_text="1-based position in the route sequence.",
                        verbose_name="Stop order",
                    ),
                ),
                (
                    "duration_at_stop",
                    models.PositiveSmallIntegerField(
                        blank=True, null=True, verbose_name="Duration at stop (min)"
                    ),
                ),
                (
                    "transport_to_next",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("walking", "Walking"),
                            ("cycling", "Cycling"),
                            ("driving", "Driving"),
                            ("transit", "Public transit"),
                            ("mixed", "Mixed"),
                        ],
                        max_length=10,
                        verbose_name="Transport to next stop",
                    ),
                ),
                (
                    "notes",
                    models.CharField(
                        blank=True, max_length=500, verbose_name="Guide notes"
                    ),
                ),
                (
                    "place",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="route_entries",
                        to="places.place",
                        verbose_name="Place",
                    ),
                ),
            ],
            options={
                "verbose_name": "Route stop",
                "verbose_name_plural": "Route stops",
                "ordering": ["tour_route", "order"],
            },
        ),
        migrations.CreateModel(
            name="TourRoute",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="Created at"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated at"),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True, default=True, verbose_name="Active"
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        db_index=True, max_length=255, verbose_name="Title"
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        allow_unicode=True,
                        max_length=280,
                        unique=True,
                        verbose_name="Slug",
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Description"),
                ),
                (
                    "cover_image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to=routes.models.route_cover_path,
                        verbose_name="Cover image",
                    ),
                ),
                (
                    "transport_mode",
                    models.CharField(
                        choices=[
                            ("walking", "Walking"),
                            ("cycling", "Cycling"),
                            ("driving", "Driving"),
                            ("transit", "Public transit"),
                            ("mixed", "Mixed"),
                        ],
                        db_index=True,
                        default="walking",
                        max_length=10,
                        verbose_name="Transport mode",
                    ),
                ),
                (
                    "difficulty",
                    models.CharField(
                        choices=[
                            ("easy", "Easy"),
                            ("moderate", "Moderate"),
                            ("hard", "Hard"),
                        ],
                        db_index=True,
                        default="easy",
                        max_length=10,
                        verbose_name="Difficulty",
                    ),
                ),
                (
                    "estimated_duration",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        help_text="Total time including stops, in minutes.",
                        null=True,
                        verbose_name="Estimated duration (min)",
                    ),
                ),
                (
                    "distance",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="Distance (metres)"
                    ),
                ),
                (
                    "map_data",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="GeoJSON LineString or Google encoded polyline for the route path.",
                        verbose_name="Map data",
                    ),
                ),
                (
                    "is_featured",
                    models.BooleanField(
                        db_index=True, default=False, verbose_name="Featured"
                    ),
                ),
                (
                    "view_count",
                    models.PositiveIntegerField(default=0, verbose_name="View count"),
                ),
                (
                    "meta_title",
                    models.CharField(
                        blank=True, max_length=70, verbose_name="Meta title"
                    ),
                ),
                (
                    "meta_description",
                    models.CharField(
                        blank=True, max_length=160, verbose_name="Meta description"
                    ),
                ),
                (
                    "places",
                    models.ManyToManyField(
                        related_name="tour_routes",
                        through="routes.RoutePlace",
                        to="places.place",
                        verbose_name="Places",
                    ),
                ),
            ],
            options={
                "verbose_name": "Tour route",
                "verbose_name_plural": "Tour routes",
                "ordering": ["-is_featured", "title"],
            },
        ),
        migrations.AddField(
            model_name="routeplace",
            name="tour_route",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="route_places",
                to="routes.tourroute",
                verbose_name="Tour route",
            ),
        ),
        migrations.AddIndex(
            model_name="tourroute",
            index=models.Index(
                fields=["is_featured", "is_active"], name="idx_route_featured_active"
            ),
        ),
        migrations.AddIndex(
            model_name="tourroute",
            index=models.Index(
                fields=["transport_mode", "is_active"], name="idx_route_mode_active"
            ),
        ),
        migrations.AddConstraint(
            model_name="routeplace",
            constraint=models.UniqueConstraint(
                fields=("tour_route", "place"), name="unique_route_place"
            ),
        ),
        migrations.AddConstraint(
            model_name="routeplace",
            constraint=models.UniqueConstraint(
                fields=("tour_route", "order"), name="unique_route_stop_order"
            ),
        ),
    ]
