# Generated by Django 5.0.1 on 2026-05-28 03:37

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("routes", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="tourroute",
            options={
                "ordering": ["-is_featured", "-created_at"],
                "verbose_name": "Tour route",
                "verbose_name_plural": "Tour routes",
            },
        ),
    ]
