# Generated by Django 5.0.1 on 2026-05-17 19:33

import django.core.validators
import django.db.models.deletion
import reviews.models
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("places", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ReviewImage",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "image",
                    models.ImageField(
                        upload_to=reviews.models.review_image_path, verbose_name="Image"
                    ),
                ),
                (
                    "order",
                    models.PositiveSmallIntegerField(default=0, verbose_name="Order"),
                ),
            ],
            options={
                "verbose_name": "Review image",
                "verbose_name_plural": "Review images",
                "ordering": ["review", "order"],
            },
        ),
        migrations.CreateModel(
            name="Review",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "rating",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (1, "★ Poor"),
                            (2, "★★ Fair"),
                            (3, "★★★ Good"),
                            (4, "★★★★ Very Good"),
                            (5, "★★★★★ Excellent"),
                        ],
                        db_index=True,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ],
                        verbose_name="Rating",
                    ),
                ),
                ("comment", models.TextField(blank=True, verbose_name="Comment")),
                (
                    "is_approved",
                    models.BooleanField(
                        db_index=True,
                        default=True,
                        help_text="Unapproved reviews are hidden from public API.",
                        verbose_name="Approved",
                    ),
                ),
                (
                    "is_flagged",
                    models.BooleanField(
                        db_index=True,
                        default=False,
                        help_text="Flagged by another user for moderation review.",
                        verbose_name="Flagged",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="Created at"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated at"),
                ),
                (
                    "place",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reviews",
                        to="places.place",
                        verbose_name="Place",
                    ),
                ),
            ],
            options={
                "verbose_name": "Review",
                "verbose_name_plural": "Reviews",
                "ordering": ["-created_at"],
            },
        ),
    ]
