# Generated by Django 5.0.1 on 2026-05-17 19:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("reviews", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="review",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="reviews",
                to=settings.AUTH_USER_MODEL,
                verbose_name="User",
            ),
        ),
        migrations.AddField(
            model_name="reviewimage",
            name="review",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="images",
                to="reviews.review",
                verbose_name="Review",
            ),
        ),
        migrations.AddIndex(
            model_name="review",
            index=models.Index(
                fields=["place", "rating"], name="idx_review_place_rating"
            ),
        ),
        migrations.AddIndex(
            model_name="review",
            index=models.Index(
                fields=["place", "is_approved"], name="idx_review_place_approved"
            ),
        ),
        migrations.AddIndex(
            model_name="review",
            index=models.Index(
                fields=["user", "created_at"], name="idx_review_user_timeline"
            ),
        ),
        migrations.AddConstraint(
            model_name="review",
            constraint=models.UniqueConstraint(
                fields=("user", "place"), name="unique_user_place_review"
            ),
        ),
        migrations.AddConstraint(
            model_name="reviewimage",
            constraint=models.UniqueConstraint(
                fields=("review", "order"), name="unique_review_image_order"
            ),
        ),
    ]
