# Generated by Django 5.0.1 on 2026-05-28 03:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("reviews", "0002_initial"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="reviewimage",
            index=models.Index(
                fields=["review", "order"], name="idx_review_image_order"
            ),
        ),
    ]
